name: Check

on: [push]

jobs:
  build:
    name: Build, Test & Prettier

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      CI: true

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm ci

    - name: build
      run: npm run build

    - name: prettier
      run: npm run prettier:check
